language: java

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
  - tar -zxf android-sdk_r20.0.3-linux.tgz
  - export ANDROID_HOME=~/build/PSDev/LicensesDialog/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter tool,platform-tool,android-16 --no-ui --force

install: mvn install -DskipTests=true -Dgpg.skip=true
